# Generated by Django 5.1.6 on 2026-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='primary_cta_url',
            field=models.CharField(default='/program', max_length=200),
        ),
    ]
